from enum import Enum


class City(str, Enum):
    TAIPEI = "臺北市"
    NEW_TAIPEI = "新北市"
    KEELUNG = "基隆市"
    TAOYUAN = "桃園市"
    HSINCHU_COUNTY = "新竹縣"
    HSINCHU_CITY = "新竹市"
    MIAOLI = "苗栗縣"
    TAICHUNG = "臺中市"
    NANTOU = "南投縣"
    CHANGHUA = "彰化縣"
    YUNLIN = "雲林縣"
    CHIAYI_COUNTY = "嘉義縣"
    CHIAYI_CITY = "嘉義市"
    TAINAN = "臺南市"
    KAOHSIUNG = "高雄市"
    PINGTUNG = "屏東縣"
    YILAN = "宜蘭縣"
    HUALIEN = "花蓮縣"
    TAITUNG = "臺東縣"
    PENGHU = "澎湖縣"
    KINMEN = "金門縣"
    LIENCHIANG = "連江縣"
